version: '2'

services:
  app:
    image: 'manager:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

#
#version: '3'
#services:
#  service1:
#    build:
#      context: ./service1
#      dockerfile: Dockerfile
#    ports:
#      - 8001:8001
#    networks:
#      - mynetwork
#
#  service2:
#    build:
#      context: ./service2
#      dockerfile: Dockerfile
#    ports:
#      - 8002:8002
#    networks:
#      - mynetwork
#
#networks:
#  mynetwork:
#